### ISSUE TITLE
Mention what to do in register() and getRegistration() if there is no active SW

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/push-api#100] opened 2014-12-18 15:07 UTC
Chromium implementation throws an exception. I'm not sure if that's something we can actually hit.

@mvano ?

**Comment by johnmellor** [comment] 2014-12-18 15:44
A common case where I think we might hit this is:

``` js
navigator.serviceWorker.register(...).then(function(serviceWorkerRegistration) {
    // This is INCORRECT: serviceWorkerRegistration might not be active yet!
    // It should wait for navigator.serviceWorker.ready instead to get an active worker.
    serviceWorkerRegistration.pushManager.register(...);
});
```

Another case is that the website could keep a reference to the PushManager for an active SWR, then the SW might asynchronously uninstall (unregister) itself in the background, then the website might try to use the PushManager.

The spec currently has a catch-all "If there is an error, reject promise with a DOMException whose name is "AbortError" and terminate these steps". Since the code sample above might be a common mistake, we should make sure these errors are logged with clear descriptions.

@jakearchibald might have thoughts on how to avoid developers falling into this trap.

**Comment by mvano** [comment] 2015-01-15 18:53
This is a duplicate of issue #92

**Closed as completed** 2015-01-15 18:53 UTC
Labels: duplicate, api
