### ISSUE TITLE
Have PermissionDeniedError added to WebIDL

### ISSUE THREAD

**Issue by foolip** [w3c/push-api#186] opened 2016-02-19 07:38 UTC
https://w3c.github.io/push-api/#exceptions

This should ideally be in http://heycam.github.io/webidl/#dfn-error-names-table so that other specifications can use it. Please file an issue at https://github.com/heycam/webidl/issues if you agree.

Note that `NotAllowedError` was added in https://github.com/heycam/webidl/pull/85 and this is very similar. It might not make sense to keep both, which would be resolved by trying to get both into the same spec :)

**Comment by mvano** [comment] 2016-02-19 14:03
This is a duplicate of #107. I hope you don't mind if I close this one.

As to the idea: it would be real nice to get this formalized.

**Closed as completed by mvano** 2016-02-19 14:03 UTC

**Comment by foolip** [comment] 2016-02-22 08:39
Thanks, will comment in Bugzilla.
